name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm ci

      - name: Test
        run: npm run test
